name: Build and Test Express.js Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.1'
      
      # Step 3: Installing dependencies
      - name: Run npm install
        run: npm install
        working-directory: /home/runner/work/express-server/express-server/backend

      # Step 4: Run tests
      - name: Run tests
        run: npm test

