name: Build and Test Express.js Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.1'
      
      # Step 3: Installing dependencies
      - name: Run npm install
        run: npm install
        working-directory: /home/runner/work/express-server/express-server/backend

      # Step 4: Run tests
      - name: Run tests
        run: npm test
        working-directory: /home/runner/work/express-server/express-server/backend
      
      # Step 5: Build Docker image with commit ID as tag (only if tests pass)
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERID }}/express-server:${{ github.sha }} .
        working-directory: /home/runner/work/express-server/express-server/
      
      # Step 6: Push Docker image to Docker Hub (only if tests pass)
      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/express-server:${{ github.sha }}

